import org.jetbrains.kotlin.gradle.dsl.JsModuleKind

plugins {
    kotlin("multiplatform") version "2.3.20"
    kotlin("plugin.serialization") version "2.3.20"
    kotlin("plugin.compose") version "2.3.20"
    id("org.jetbrains.compose") version "1.11.1"
}

group = "ge.dakalebi"
version = "1.0.0"

// ---------------------------------------------------------------- build info
//
// The app deploys continuously from main, so there is no release to name and
// the `version` above never moves. What actually identifies a deployment is the
// CI run that produced it, the commit it came from, and when it went live — so
// those three are baked in here and shown in the drawer.

fun git(vararg args: String): String = runCatching {
    providers.exec { commandLine(listOf("git") + args) }
        .standardOutput.asText.get().trim()
}.getOrDefault("")

val ciRunNumber: String = providers.environmentVariable("GITHUB_RUN_NUMBER").getOrElse("")
val gitCommit: String = git("rev-parse", "--short", "HEAD").ifBlank { "unknown" }

/**
 * On CI this is the moment of the build, which is within a minute of going
 * live. Locally it is the *commit* time instead: a wall clock would make the
 * generated file differ on every invocation and force a full Kotlin/JS
 * recompile each build — a slow price for a line of footer text.
 */
val publishedAtMillis: Long = if (ciRunNumber.isNotBlank()) {
    System.currentTimeMillis()
} else {
    git("log", "-1", "--format=%ct").toLongOrNull()?.times(1000) ?: 0L
}

/** Derived rather than hardcoded — this repo has already changed owners once. */
val repoUrl: String = git("config", "--get", "remote.origin.url")
    .removeSuffix(".git")
    .replace("git@github.com:", "https://github.com/")

val generateBuildInfo by tasks.registering {
    // Everything the action touches is copied into locals first. Referring to
    // the script's own properties from inside doLast captures the build script
    // object, which the configuration cache cannot serialise.
    val outputRoot = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    val buildNumber = ciRunNumber.ifBlank { "dev" }
    val commit = gitCommit
    val publishedAt = publishedAtMillis
    val repo = repoUrl

    inputs.property("buildNumber", buildNumber)
    inputs.property("commit", commit)
    inputs.property("publishedAtMillis", publishedAt)
    inputs.property("repoUrl", repo)
    outputs.dir(outputRoot)

    doLast {
        val dir = outputRoot.get().asFile.resolve("ge/dakalebi/app")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            package ge.dakalebi.app

            /** Generated by the `generateBuildInfo` Gradle task. Do not edit. */
            object BuildInfo {
                /** CI run number, or "dev" for a build made on someone's machine. */
                const val BUILD_NUMBER: String = "$buildNumber"
                const val COMMIT: String = "$commit"
                const val PUBLISHED_AT_MILLIS: Double = $publishedAt.0
                const val REPO_URL: String = "$repo"

                val isDevBuild: Boolean get() = BUILD_NUMBER == "dev"

                val commitUrl: String? get() =
                    if (REPO_URL.isBlank() || COMMIT == "unknown") null
                    else "${'$'}REPO_URL/commit/${'$'}COMMIT"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    js(IR) {
        // CommonJS rather than the UMD default: the Firebase SDK is only
        // reachable as a module, so `@JsModule` externals would otherwise need a
        // `@JsNonModule` global fallback that does not exist.
        compilerOptions {
            moduleKind.set(JsModuleKind.MODULE_COMMONJS)
        }
        browser {
            commonWebpackConfig {
                outputFileName = "app.js"
            }
            testTask { enabled = false }
        }
        binaries.executable()
    }

    sourceSets {
        getByName("jsMain") {
            // Passing the task provider wires the dependency automatically, so
            // BuildInfo.kt is always regenerated before compilation.
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation("org.jetbrains.compose.runtime:runtime:1.11.1")
                implementation("org.jetbrains.compose.html:html-core:1.11.1")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
                implementation(npm("firebase", "12.17.0"))
            }
        }
    }
}
