// Everything the web app and a future Android TV app both need.
//
// Deliberately not an application: no `binaries.executable()`, no webpack, and no
// `moduleKind`. This produces klibs, and the module that links them into a bundle
// is the one that gets to decide the output shape. `moduleKind = COMMONJS` stays
// in the root build file with the `@JsModule` externals that force it.
//
// Plugin versions come from the root build file, which resolves them for the
// whole build. Adding a version here would let the two drift.
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    kotlin("plugin.compose")
}

// ---------------------------------------------------------------- build info
//
// The app deploys continuously from main, so there is no release to name and the
// root project's `version` never moves. What actually identifies a deployment is
// the CI run that produced it, the commit it came from, and when it went live —
// so those three are baked in here and shown in the drawer.
//
// Generated into `commonMain`, which is why it lives in this module rather than
// in the app that shows it: both front ends print the same stamp, and neither can
// print one the other cannot.

fun git(vararg args: String): String = runCatching {
    providers.exec { commandLine(listOf("git") + args) }
        .standardOutput.asText.get().trim()
}.getOrDefault("")

val ciRunNumber: String = providers.environmentVariable("GITHUB_RUN_NUMBER").getOrElse("")
val gitCommit: String = git("rev-parse", "--short", "HEAD").ifBlank { "unknown" }

/**
 * On CI this is the moment of the build, which is within a minute of going
 * live. Locally it is the *commit* time instead: a wall clock would make the
 * generated file differ on every invocation and force a full Kotlin/JS
 * recompile each build — a slow price for a line of footer text.
 */
val publishedAtMillis: Long = if (ciRunNumber.isNotBlank()) {
    System.currentTimeMillis()
} else {
    git("log", "-1", "--format=%ct").toLongOrNull()?.times(1000) ?: 0L
}

/** Derived rather than hardcoded — this repo has already changed owners once. */
val repoUrl: String = git("config", "--get", "remote.origin.url")
    .removeSuffix(".git")
    .replace("git@github.com:", "https://github.com/")

// `tasks.register`, not the `by tasks.registering` delegate: that delegate is
// deprecated in Gradle 9.6 and removed in 10.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    // Everything the action touches is copied into locals first. Referring to
    // the script's own properties from inside doLast captures the build script
    // object, which the configuration cache cannot serialise.
    val outputRoot = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    val buildNumber = ciRunNumber.ifBlank { "dev" }
    val commit = gitCommit
    val publishedAt = publishedAtMillis
    val repo = repoUrl

    inputs.property("buildNumber", buildNumber)
    inputs.property("commit", commit)
    inputs.property("publishedAtMillis", publishedAt)
    inputs.property("repoUrl", repo)
    outputs.dir(outputRoot)

    doLast {
        val dir = outputRoot.get().asFile.resolve("ge/dakalebi/core")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            package ge.dakalebi.core

            /** Generated by the `generateBuildInfo` Gradle task. Do not edit. */
            object BuildInfo {
                /** CI run number, or "dev" for a build made on someone's machine. */
                const val BUILD_NUMBER: String = "$buildNumber"
                const val COMMIT: String = "$commit"
                const val PUBLISHED_AT_MILLIS: Double = $publishedAt.0
                const val REPO_URL: String = "$repo"

                val isDevBuild: Boolean get() = BUILD_NUMBER == "dev"

                val commitUrl: String? get() =
                    if (REPO_URL.isBlank() || COMMIT == "unknown") null
                    else "${'$'}REPO_URL/commit/${'$'}COMMIT"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    js(IR) {
        // The browser sub-target exists so the root module's webpack build can
        // consume this klib. Nothing here is testable in a browser, and the
        // domain is testable without one, so tests run on Node.
        browser {
            testTask { enabled = false }
        }
        nodejs()
    }

    // The Version 2.0 `:web` app is Compose Multiplatform on wasmJs, so it needs this
    // module's klib compiled for wasm too. Additive: the root app still consumes the
    // `js(IR)` klib. Only `commonMain`'s three `expect` functions need wasm `actual`s.
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser {
            testTask { enabled = false }
        }
    }

    sourceSets {
        // The wasm actuals are typed JS interop, which is still opt-in. Declared here so the
        // build stays warning-free without a file annotation on every actual.
        all {
            languageSettings.optIn("kotlin.js.ExperimentalWasmJsInterop")
        }

        commonMain {
            // Passing the task provider wires the dependency automatically, so
            // BuildInfo.kt is always regenerated before compilation.
            kotlin.srcDir(generateBuildInfo)
        }

        commonMain.dependencies {
            // `api`, not `implementation`: `CompositionLocal`, `CoroutineScope` and
            // the state holders' types all appear in signatures the root module
            // reads, so consumers need them on their own compile classpath.
            api("org.jetbrains.compose.runtime:runtime:1.11.1")
            api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
            // Private: only the Formula DTOs and the catalog cache serialise.
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0")
        }
    }
}
